// GENERATED by tool/_gen_str_blobs.dart — DO NOT EDIT BY HAND.
import 'seal_gate.dart';

// ============================================================
// VEILED STRINGS — wire/game strings resolved through the sealer
// ============================================================
// Primary source is the native library (`SealGate.str`), where
// each value lives only as an XOR-masked byte array. When the
// gate is unavailable (off-Android / desktop / dev) the code-unit
// fallback below is used: a `List<int>` is not matched by a
// plaintext string scanner, so no greppable wire literal reaches
// the AOT image (same convention as device_signature.dart).
// ============================================================

abstract final class VeiledStrings {
  /// Resolve the obfuscated value for an opaque [name].
  static String get(String name) {
    final String? native = SealGate.instance.str(name);
    if (native != null && native.isNotEmpty) return native;
    final List<int>? seed = _seeds[name];
    return seed == null ? '' : String.fromCharCodes(seed);
  }

  static const Map<String, List<int>> _seeds = <String, List<int>>{
    'rm_u': <int>[117, 110, 100, 101, 99, 105, 100, 101, 100],
    'rm_p': <int>[112, 111, 114, 116, 97, 108],
    'rm_n': <int>[110, 97, 116, 105, 118, 101],
    'rm_w': <int>[119, 101, 98],
    'rm_g': <int>[103, 97, 109, 101],
    'k_url': <int>[117, 114, 108],
    'k_locale': <int>[108, 111, 99, 97, 108, 101],
    'k_payload': <int>[112, 97, 121, 108, 111, 97, 100],
    'k_afst': <int>[97, 102, 95, 115, 116, 97, 116, 117, 115],
    'k_fbp': <int>[102, 105, 114, 101, 98, 97, 115, 101, 95, 112, 114, 111, 106, 101, 99, 116, 95, 105, 100],
    'e_tmr': <int>[116, 111, 111, 95, 109, 97, 110, 121, 95, 114, 101, 100, 105, 114, 101, 99, 116, 115],
    'e_gu': <int>[103, 97, 116, 101, 95, 117, 110, 97, 118, 97, 105, 108, 97, 98, 108, 101],
    'h_ua': <int>[85, 115, 101, 114, 45, 65, 103, 101, 110, 116],
    'mc_cut': <int>[99, 117, 116, 111, 117, 116],
    'in_top': <int>[116, 111, 112],
    'in_left': <int>[108, 101, 102, 116],
    'in_right': <int>[114, 105, 103, 104, 116],
    'g_cb': <int>[67, 111, 108, 108, 101, 99, 116, 32, 98, 111, 110, 117, 115],
    'g_bi': <int>[66, 111, 110, 117, 115, 32, 105, 110, 32, 123, 104, 125, 104, 32, 123, 109, 125, 109],
    'g_notif': <int>[65, 76, 76, 79, 87, 32, 78, 79, 84, 73, 70, 73, 67, 65, 84, 73, 79, 78, 83, 32, 65, 66, 79, 85, 84, 32, 66, 79, 78, 85, 83, 69, 83, 32, 65, 78, 68, 32, 80, 82, 79, 77, 79, 83],
    'g_chn': <int>[66, 111, 110, 117, 115, 101, 115, 32, 38, 32, 80, 114, 111, 109, 111, 115],
    'g_chd': <int>[66, 111, 110, 117, 115, 32, 100, 114, 111, 112, 115, 44, 32, 112, 114, 111, 109, 111, 115, 32, 97, 110, 100, 32, 114, 101, 119, 97, 114, 100, 32, 114, 101, 109, 105, 110, 100, 101, 114, 115],
  };
}
